import { Divider, Link, Text, WidgetCard, WidgetItemField } from "@node42/ui-kit";
import { AppShell } from "../AppShell";
import report from "../data";

export default function About() {
  const { meta, product } = report;

  return (
    <AppShell title="About this report" description={meta.subtitle}>
      <section
        style={{ display: "flex", flexDirection: "column", gap: "var(--space-300)" }}
      >
        <Text variant="page-chapter">The question</Text>
        <Text variant="b1" style={{ color: "var(--text-body)" }}>
          {meta.question}
        </Text>
      </section>

      <section
        style={{ display: "flex", flexDirection: "column", gap: "var(--space-300)" }}
      >
        <Text variant="page-chapter">Methodology recap</Text>
        <WidgetCard title="PCM workflow steps" span={12}>
          <div
            style={{ display: "flex", flexDirection: "column", gap: "var(--space-300)" }}
          >
            {meta.methodology.map((step, i) => (
              <WidgetItemField key={step} variant="vertical" label={`0${i + 1}`}>
                {step}
              </WidgetItemField>
            ))}
          </div>
        </WidgetCard>
      </section>

      <section
        style={{ display: "flex", flexDirection: "column", gap: "var(--space-300)" }}
      >
        <Text variant="page-chapter">Provenance</Text>
        <WidgetCard title="Provenance" span={12}>
          <div
            style={{ display: "flex", flexDirection: "column", gap: "var(--space-300)" }}
          >
            <WidgetItemField variant="long-title" label="Vendor">
              {product.vendor}
            </WidgetItemField>
            <WidgetItemField variant="long-title" label="Report">
              {meta.title}
            </WidgetItemField>
            <WidgetItemField variant="long-title" label="Subtitle">
              {meta.subtitle}
            </WidgetItemField>
            <Divider />
            <Text variant="b2">
              Generated by the Node42 PCM (Product–Commodity–Market) new-markets
              workflow — a universal Digital Twin analysis that decomposes the
              product, discovers candidate markets along the BOM and Process-VN
              paths, ranks them on a six-factor composite, and resolves each
              leading market down to its value-network anchors and stakeholders.
            </Text>
            <Link href="https://node42.io">node42.io</Link>
          </div>
        </WidgetCard>
      </section>
    </AppShell>
  );
}
